### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by xiaowowwwww** [RylonW/CycleSE-GAN#1]
Hello, excuse me, I have some doubts about the Settings of the data set, can you tell me the specific Settings of the data set? Thank you very much!

**Comment by RylonW** [comment]
Sure! Please wait for some time. I will reply you soon!

**Comment by xiaowowwwww** [comment]
Thank you for your reply. I would like to ask if I can send the pre-training model, because I can't get the result after training, and I can't get the result when testing without reporting errors. I want to know whether I made a mistake in training. Thank you very much!

**Comment by RylonW** [comment]
Hi! I have uploaded the datatset on Dropbox. Please check to see if you were able to download it successfully.

**Comment by xiaowowwwww** [comment]
Thank you very much! I can download it already.
